baseURL: "https://vigil-hayes.github.io"
title: Morgan Vigil-Hayes
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Selected Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2

params:
    description: "I am an associate professor of computer science in the School of Informatics, Computing, and Cyber Systems at Northern Arizona University. As a computer scientist, my research revolves around characterizing network trace data and social media data to gain insights into the utilization and adaptation of existing networked systems within underserved communities. Leveraging these insights, I design novel networked systems that better align with the specific needs, values, and usage patterns of these communities, aiming to create more inclusive and human-centric technological solutions.
In particular, my work centers the information needs and practices of rural and tribal communities in North America with the goal of addressing longstanding digital and social inequities.

I teach graduate and undergraduate computer science courses related to computer networks and social computing as well as an Honors seminar course that examines the ethical concerns surrounding emergent digital technologies.
"
    author: Morgan Vigil-Hayes
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2023"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Morgan Vigil-Hayes
          subtitle: "I am an associate professor of computer science in the School of Informatics, Computing, and Cyber Systems at Northern Arizona University. As a computer scientist, my research revolves around characterizing network trace data and social media data to gain insights into the utilization and adaptation of existing networked systems within underserved communities. Leveraging these insights, I design novel networked systems that better align with the specific needs, values, and usage patterns of these communities, aiming to create more inclusive and human-centric technological solutions.
In particular, my work centers the information needs and practices of rural and tribal communities in North America with the goal of addressing longstanding digital and social inequities.

I teach graduate and undergraduate computer science courses related to computer networks and social computing as well as an honors course that examines the ethical concerns surrounding emergent digital technologies."
          imageUrl: "mvh_small_square.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Morgan Vigil-Hayes
          buttons:
            - name: Selected Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Projects
              url: projects/
    socialIcons:
        - name: CV
          url: Vigil-Hayes_CV_2023-11.pdf
        - name: Email
          url: mailto:morgan.vigil-hayes@nau.edu
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=ymJqHu4AAAAJ
        - name: GitHub
          url: https://github.com/CANIS-NAU

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "M. Vigil-Hayes"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
